from .layer import Layer, LayerPointProvider, Point
from .csv_layer import CSVImporter
import folium

HOSPITAL_IMPORTER: CSVImporter

class HospitalLayerPointProvider(LayerPointProvider):
    def __init__(self) -> None: ...
    def point_list(self) -> list[Point]: ...

class HospitalLayer(Layer):
    points: HospitalLayerPointProvider

    def __init__(self) -> None: ...
    def lat_long_provider(self) -> HospitalLayerPointProvider: ...
    def name(self) -> str: ...
    def radius(self) -> int: ...    
    def icon(self) -> folium.Icon: ...
