from .layer import Layer, LayerPointProvider, Point
from .csv_layer import CSVImporter

TJ_IMPORTER: CSVImporter

class TJLayerPointProvider(LayerPointProvider):
    def __init__(self) -> None: ...
    def point_list(self) -> list[Point]: ...

class TJLayer(Layer):
    points: TJLayerPointProvider

    def __init__(self) -> None: ...
    def lat_long_provider(self) -> TJLayerPointProvider: ...
    def name(self) -> str: ...
